# BetterChat
# Version ${project.version}
# Please report bugs as an issue here: https://github.com/connorlinfoot/BetterChat
#
# You MUST have a default channel. If the default channel is removed the plugin will not start!

Settings:
  Staff Chat Enabled: true
  Default Channel: Default

Channels:
  Default:
    Permission Required: false
  Channel A:
    Permission Required: true
  Channel B:
    Permission Required: true
  Channel C:
    Permission Required: false