# BetterChat
# Version ${project.version}
# Please read documentation on using the plugin here: https://github.com/connorlinfoot/BetterChat

Settings:
  Staff Chat Enabled: true
  Staff Chat Prefix: "&7[&bStaff Chat&7]"
  Default Channel: Default
  Enable Chat Color: true
  Remember Player Channels: false

Channels:
  Default:
    Permission Required: false
  Channel A:
    Permission Required: true
    Prefix: "&7[&bChannel A&7]"
  Channel B:
    Permission Required: true
    Prefix: "&7[&bChannel B&7]"
    Command: "channela"
  Channel C:
    Permission Required: false
    Prefix: "&7[&bChannel C&7]"
