# BetterChat
# Version ${project.version}
# Please report bugs as an issue here: https://github.com/connorlinfoot/BetterChat
#
# Do NOT remove the "Default" channel. If the default channel is removed the plugin will not start!

Staff Chat Enabled: true

Channels:
  Default:
    Permission Required: false
  Channel A:
    Permission Required: true
  Channel B:
    Permission Required: true
  Channel C:
    Permission Required: false