# BetterChat
# Version ${project.version}
# Please report bugs as an issue here: https://github.com/connorlinfoot/BetterChat
#
# You MUST have a default channel. If the default channel is removed the plugin will not start!

Settings:
  Staff Chat Enabled: true
  Staff Chat Prefix: "&7[&bStaff Chat&7]"
  Default Channel: Default
  Enable Chat Color: true

Channels:
  Default:
    Permission Required: false
  Channel A:
    Permission Required: true
    Prefix: "&7[&bChannel A&7]"
  Channel B:
    Permission Required: true
    Prefix: "&7[&bChannel B&7]"
  Channel C:
    Permission Required: false
    Prefix: "&7[&bChannel C&7]"
