name: ${project.artifactId}
description: ${project.description}
main: com.connorlinfoot.betterchat.Bukkit.BetterChat
version: ${project.version}
commands:
  staffchat:
    description: Send a message to all staff
    aliases: [sc]
  channel:
    description: Switch which chat channel you are currently in
    aliases: [switchchannel,c]
  whatchannel:
    description: Find what channel a specific player is in
    aliases: [wc]
  betterchat:
    description: The main BetterChat command
    aliases: [bc]
  mute:
    description: Mute players from talking in any channel
permissions:
  betterchat.staff:
    default: op
  betterchat.all:
    default: op
  betterchat.admin:
    default: op